before:
  hooks:
    - make clean
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - freebsd
    - openbsd
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  # ignore:
  # - goos: openbsd
  #   goarch: arm
  # - goos: openbsd
  #   goarch: arm64
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews: 
- 
  name: harsh
  tap:
    owner: wakatara
    name: homebrew-tap
  description: habit tracking for geeks. A minimalist CLI for examining your habits. 
  homepage: https://github.com/wakatara/harsh
  license: MIT
  test: |
    system "#{bin}/harsh --version"
snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}'
    summary: habit tracking for geeks. A minimalist CLI for examining your habits.
    description: |
      Harsh provides a simple, portable, minimalist command line interface for
      tracking and examining your habits with text files and actionable
      consistency graphs, sparklines, and scoring to let you know how you are 
      doing on progressing (or breaking) your habits.
      https://github.com/wakatara/harsh
    grade: stable
    confinement: strict
    license: MIT
    publish: true
